### ISSUE TITLE
The automation starts but in ar Quora and script said that the password and email incorrect while they are not.

### ISSUE THREAD

**Issue by ghost** [Ganofins/Quora-Request-Automation#2]
DevTools listening on ws://127.0.0.1:42291/devtools/browser/17bd05b2-eb40-4723-8e82-da164edfcd4b
[1080:1948:0423/125102.804:ERROR:browser_switcher_service.cc(238)] XXX Init()
[1080:1948:0423/125106.529:ERROR:device_event_log_impl.cc(162)] [12:51:06.528] Bluetooth: bluetooth_adapter_winrt.cc:1055 Getting Default Adapter failed.
Invalid Email or Password
PS C:\Users\TOSHIBA\Downloads\Quora-Request-Automation-master\Quora-Request-Automation-master\Quora-Request-Automation>

**Comment by rohan-arondekar** [comment]
Same problem even for me!

**Comment by Ganofins** [comment]
There shouldn't be any such issue

Could you recheck these things -
> Your email and password in credentials.json file is correct

> You have an account on https://quora.com/partner

> You have working internet connection

Sorry for the late response 😅

Yeah the layout of the Quora site is completely changed, so the script will not work after loggin into the account but you shouldn't be seeing "incorrect email or password" error.

I am thinking about creating unofficial Quora API...😁
